apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:8+eAXb2QxwsjnLwUkiep1ejDDoBlqu4aZHy/liJ/Y2NQjLT8GtiOYMFnK5FsuqeflYT+ZETfKoQTwUc/,iv:v1Rn2kmG1h104b+Fs4qCPxBRjgS2IVPJEbvE8vNbZIY=,tag:zpIUZ5GBBZjwuRdugfZOkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWjFwVTU2cXBML1F4eFV2
            RnVCcEFUOFlvV2JVUWlvcUptdDVFNHZOekM4ClJkMGhUUUFjZXNmNld2ZjU0TnFh
            N1duTkV0U3QzV1pBbmZuS2tvL1BoaVEKLS0tIE9zS1VFOWQxT2RQSXJtZHBEQmk5
            a1pWNWY5YVRkRTBKQTV4TkpwRUpoOGsKFmY2ErZ9jbZQbD5GGaXDlzQamAd51ni+
            rSTXMqqCcY+vUww+JjksFa4v62N/9Ctt6Kz249NcGxPMHhdld4Y5tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T01:39:32Z"
    mac: ENC[AES256_GCM,data:SFEC4uDhgD4cnzUD7u6krllpr/yDTWoGsHgD9A0Zaxvd4kJAnqGqLR7YZE9WVv1FwJpEWvKoSQg2v123U62h+QirTITNgQ9jYwtaOwgVpbS3IXfn7xU9BSxIRQfFUqpTA2g9Bj4Zhb2KtnwvWm225yMbZZ2kFZU3M4PAWqxw6eU=,iv:rYIO91QbvskfFjsB42mXXVzd6pi9j6+CfFVjTy3k664=,tag:egVlsoc1+TJjgsBmQbzUhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
