apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:U8T93DXu5dMNqA==,iv:ItehRjMXoGH7tha7F/hmlH2sYGG7sUj6ryNchfh1VJs=,tag:ed+QfZndmGfmI6OR4Eapcg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:qrwvMrDNel0poGAIoNkGy3umNO4=,iv:Pvuc4IFHEqOa1/V15mdP+SY6otI+4dj6fX3jbNAaA2M=,tag:WgXH+Fj+vSH/dbfRR/Wr8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUHk1NklWWklud0pPdGtn
            aEhad3k2ZjVzTDRjekhUcHVLVmgzNmVJNG44CmJTL0VzcnROb0pSQ1UwNGFnZ1Np
            NVdjenc1N3N0T2NDeXBLYUFRZWtLYVUKLS0tIGQyMTZhL1QvTERZOU1ucVNmVytn
            OWtaQ3AzQ2xRUWR3ZTBBWVFJYURQSVUK3dasu5rWtvUnQOO0lo+r0pkKxyMXqo56
            0Qd1InKd1liAUHMt0AsMnTHmtG12ETMqe2avl2iDFlR1WtimDSZ17w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-10T01:39:31Z"
    mac: ENC[AES256_GCM,data:ITCx9JakLvmELlCJauEo9RNNM7DQdQY0wNtBecRYu2Frkxi5g1EH529y/D8HGC8OMKqAJ/zp2jpDs0V437LQIbwzzTCKEkJOwC7Hg/37mE1kO2MKLtlnBdL2Uo6IsbTcS1iD0GuxfM/HvGuAKAzHqfxUL/N/ZoO1XYwCcrwipyo=,iv:prLtp8lVaxfOXOJuBnpdaXMrCObyRw0y+PzuvefaevE=,tag:qWrPudghrgAGlOWOOjPz/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
