---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Denver"
  KUBE_VIP_ADDR: "10.10.111.150"
  METALLB_LB_RANGE: "10.10.111.100-10.10.111.110"
  METALLB_K8S_GATEWAY_ADDR: "10.10.111.100"
  METALLB_INGRESS_ADDR: "10.10.111.110"
